export { getArticleDetailsData } from "./model/selectors/articleDetailsData"
export { ArticleDetailsSlice } from "./model/slice/articleDetailsSlice"
export type { Article } from "./model/types/article"
export type { ArticleDetailsSchema } from "./model/types/articleDetailsSchema"
export { ArticleDetails } from "./ui/ArticleDetails/ArticleDetails"
