name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
        matrix:
            node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
                -name: Starting Node.js ${{matrix.node-version}}
                with:
                  node-version: ${{matrix.node-version}}
          - name: install modules
            run: npm install
          - name: build production project
            run: npm run build:prod
          - name: build dev project
            run: npm run build:dev
          - name: linting project
            run: npm run lint
          - name: linting styles
            run: npm run slint
          - name: unit testing
            run: npm run test:unit


